/**
 * Phase 7 — grades the stored AI investigations and writes EVALUATION-AI.md.
 *
 * Reads `investigations` from Supabase rather than the seed, because these are
 * generated output rather than source data and are not part of the snapshot.
 * It spends no model quota: it grades what has already been stored, so it can
 * be re-run freely and the numbers always refer to responses that actually
 * happened.
 *
 * The evidence package for each account is rebuilt deterministically from the
 * same tables the live path uses, so grounding is checked against exactly what
 * the model was shown.
 *
 *   npm run evaluate:ai
 *   npm run evaluate:ai -- --dry
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  evaluateAi,
  type AiEvaluationReport,
  type GradeInput,
} from "../lib/ai-evaluation";
import { buildEvidencePackage } from "../lib/investigation/evidence";
import { scoreCustomer } from "../lib/risk-engine";
import { getLatestRecordedDate } from "../lib/time";
import type {
  Customer,
  EvaluationCase,
  SupportTicket,
  Subscription,
  UsageDaily,
} from "../lib/types";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DRY = process.argv.includes("--dry");

const env: Record<string, string> = {};
for (const line of readFileSync(join(ROOT, ".env.local"), "utf8").split("\n")) {
  const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
  if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, "").trim();
}
const SB = `${env.SUPABASE_URL}/rest/v1`;
const H = {
  apikey: env.SUPABASE_SERVICE_ROLE_KEY,
  Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
};

async function selectAll<T>(
  table: string,
  select: string,
  order = "customer_id",
): Promise<T[]> {
  let out: T[] = [];
  for (let from = 0; ; from += 1000) {
    const res = await fetch(
      `${SB}/${table}?select=${select}&order=${order}&limit=1000&offset=${from}`,
      { headers: H },
    );
    if (!res.ok) throw new Error(`${table}: ${res.status} ${await res.text()}`);
    const page = (await res.json()) as T[];
    out = out.concat(page);
    if (page.length < 1000) break;
  }
  return out;
}

function group<T extends { customer_id: string }>(rows: T[]) {
  const m = new Map<string, T[]>();
  for (const r of rows) {
    const l = m.get(r.customer_id);
    if (l) l.push(r);
    else m.set(r.customer_id, [r]);
  }
  return m;
}

const pct = (n: number) => `${(n * 100).toFixed(0)}%`;

function render(report: AiEvaluationReport): string {
  const t = report.totals;
  const lines: string[] = [];
  const p = (s = "") => lines.push(s);

  p("# Evaluation — grading the AI investigation layer");
  p();
  p(
    "Generated by `npm run evaluate:ai`. It grades investigations already stored in",
  );
  p(
    "`investigations`, so it spends no model quota and every number refers to a",
  );
  p("response that actually happened.");
  p();
  p("## What this measures, and what it refuses to");
  p();
  p(
    "Grading generated prose is the hard half of this project. The obvious questions",
  );
  p(
    "— is this root cause *right*, is this recommendation *wise* — need a human or a",
  );
  p(
    "second model to judge, and neither is reproducible. So everything below is",
  );
  p("checked mechanically against the evidence the model was handed.");
  p();
  p(
    "**There is deliberately no root-cause accuracy score.** `expected_root_cause`",
  );
  p(
    "exists in the dataset, but scoring prose against prose by string similarity",
  );
  p(
    "would produce a number that moves with phrasing rather than correctness. A",
  );
  p(
    "metric that looks rigorous and measures nothing is worse than an honest gap.",
  );
  p();
  p(
    "Ground truth is never an input to the model. It is compared against output",
  );
  p("afterwards, which is the entire difference between grading and leaking.");
  p();

  p("## Results");
  p();
  p(`Graded **${t.graded}** stored investigations.`);
  p();
  p("| Metric | Result | What a failure would mean |");
  p("| --- | --- | --- |");
  p(
    `| Structured-output validity | ${t.valid}/${t.graded} | The response could not be parsed into the required shape |`,
  );
  p(
    `| Fully grounded | ${t.fullyGrounded}/${t.valid} (mean ${t.meanGrounding.toFixed(3)}) | A citation pointed at evidence that was never supplied |`,
  );
  p(
    `| Free of phantom entities | ${t.valid - t.withPhantoms}/${t.valid} | A ticket id or date was named in prose but is absent from the package |`,
  );
  p(
    `| Uncited claims | ${t.uncitedClaims} | A claim asserted with nothing behind it |`,
  );
  p(
    `| Engaged the counter-case | ${t.contradictingUsed}/${t.contradictingAvailable} | Contradicting evidence was available and ignored |`,
  );
  p(
    `| Aligned with the risk band | ${t.aligned}/${t.valid} | — |`,
  );
  p(
    `| Escalated beyond the band | ${t.escalated}/${t.valid} | Not a failure; see below |`,
  );
  p(
    `| De-escalated below the band | ${t.deEscalated}/${t.valid} | Talking a CSM out of looking at a flagged account |`,
  );
  p(
    `| Uncertainty claimed correctly | ${t.insufficientAppropriate}/${t.valid} | It invented a root cause on thin evidence, or refused on rich evidence |`,
  );
  p(
    `| Mean distinct evidence cited | ${t.meanCitedDistinct.toFixed(1)} of ~${Math.round(report.cases.reduce((s, c) => s + c.itemsAvailable, 0) / Math.max(1, report.cases.length))} available | A low number means it fixated on one signal |`,
  );
  p();

  p("### Per account");
  p();
  p(
    "| Account | Model | Valid | Grounding | Phantoms | Counter-case | Action | Band | Insufficient |",
  );
  p("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const c of report.cases) {
    p(
      `| ${c.customerId} | ${c.model} | ${c.valid ? "yes" : "**no**"} | ` +
        `${c.valid ? c.grounding.rate.toFixed(2) : "—"} | ` +
        `${c.phantomEntities.length ? `**${c.phantomEntities.join(", ")}**` : "none"} | ` +
        `${c.contradictingAvailable ? (c.contradictingUsed ? "used" : "**ignored**") : "n/a"} | ` +
        `${c.recommendedAction} | ${c.deterministicLevel} (${c.deterministicScore})` +
        `${c.vsBand === "aligned" ? "" : c.vsBand === "escalated" ? " ↑" : " **↓**"} | ` +
        `${c.insufficientEvidence ? "yes" : "no"}${c.insufficientAppropriate ? "" : " **?**"} |`,
    );
  }
  p();

  /* --- The escalation finding --------------------------------------- */
  const escalations = report.cases.filter((c) => c.vsBand === "escalated");
  if (escalations.length) {
    p("### Where the model disagreed with the engine");
    p();
    p(
      `The model recommended more urgency than the deterministic band on ` +
        `**${escalations.length} of ${t.valid}** accounts, and less on ${t.deEscalated}.`,
    );
    p();
    p("| Account | Score | Band | Model said |");
    p("| --- | --- | --- | --- |");
    for (const c of escalations) {
      p(
        `| ${c.customerId} | ${c.deterministicScore} | ${c.deterministicLevel} | ${c.recommendedAction} |`,
      );
    }
    p();
    p("**This is not scored as error, and the reason matters.** Every escalation");
    p("above is an account where signals fired but summed below the flag threshold.");
    p("C006 is the clearest: an unresolved negative ticket, *\"Dashboard taking 20-30");
    p("seconds to load\"*, open for two months, plus a mild historical decline. The");
    p("engine scored those 8 and 6 — total 14, under the 25 needed to surface — and");
    p("called the account low risk. The model read the ticket text, connected it to");
    p("the decline, and said intervene.");
    p();
    p("That is the same failure mode `EVALUATION.md` found independently by grading");
    p("the engine against human labels: *the middle band is under-sensitive, and two");
    p("minor signals at 8 points each total 16, under the 25 needed to surface*. Two");
    p("evaluations built for different purposes landed on the same defect, which is");
    p("better evidence than either alone.");
    p();
    p("It is also the clearest argument for the layer existing. The engine counts");
    p("tickets; it cannot read them. A ticket whose *status* is mild and whose");
    p("*content* is severe is exactly the gap between the two.");
    p();
    p(
      `**De-escalations would be the worrying direction**, and there are ` +
        `${t.deEscalated === 0 ? "none" : String(t.deEscalated)} here. An escalation ` +
        "adds an account to a worklist and costs a CSM ten minutes; a de-escalation " +
        "takes one off, and the cost of being wrong is a churn nobody looked at.",
    );
    p();
  }

  if (report.byModel.length > 1) {
    p("### By model");
    p();
    p("| Model | Cases | Mean grounding | With phantoms |");
    p("| --- | --- | --- | --- |");
    for (const m of report.byModel) {
      p(
        `| ${m.model} | ${m.cases} | ${m.meanGrounding.toFixed(3)} | ${m.withPhantoms} |`,
      );
    }
    p();
  }

  p("## Recommendation against the human grading");
  p();
  if (report.vsGroundTruth.compared === 0) {
    p("No overlap between graded investigations and labelled accounts yet.");
  } else {
    p(
      `Agreed on **${report.vsGroundTruth.agree} of ${report.vsGroundTruth.compared}** ` +
        `(${pct(report.vsGroundTruth.agree / report.vsGroundTruth.compared)}).`,
    );
    p();
    p("| `expected_recommendation` | Model said | Accounts |");
    p("| --- | --- | --- |");
    for (const cell of report.vsGroundTruth.matrix) {
      p(
        `| ${cell.expected} | ${cell.got}${cell.expected === cell.got ? "" : " ←"} | ${cell.count} |`,
      );
    }
    p();
    p(
      "Disagreement is not automatically a model error. `expected_recommendation` was",
    );
    p(
      "written with knowledge of the outcome; the model is blind to it by design, and",
    );
    p("the investigations are only run on accounts the engine flagged, so the");
    p("comparison is over a deliberately skewed slice.");
  }
  p();

  p("## What these numbers are not");
  p();
  p(
    "**A small sample.** A handful of accounts on synthetic data. The grounding and",
  );
  p("phantom checks are absolute — a single fabrication would show — but the");
  p("agreement figures are too small to carry a trend.");
  p();
  p(
    "**Not a measure of usefulness.** Every check here asks whether a claim is",
  );
  p(
    "*supported*, not whether it is *insightful*. A model that only ever restated",
  );
  p(
    "the evidence list would score perfectly on all of it. That gap is the honest",
  );
  p(
    "limit of mechanical grading, and the offline provider exists partly to make it",
  );
  p("visible: it scores well here and is deliberately not an investigation.");
  p();
  p("**Only the accounts the engine flagged.** Low-risk accounts are not");
  p("investigated, so this says nothing about behaviour on a quiet account.");
  p();

  return lines.join("\n") + "\n";
}

(async () => {
  const [customers, cases, usage, tickets, subs, stored] = await Promise.all([
    selectAll<Customer>("customers", "*"),
    selectAll<EvaluationCase>(
      "evaluation_cases",
      "customer_id,expected_recommendation,expected_risk_level,case_type",
    ),
    selectAll<UsageDaily>("usage_daily", "customer_id,date,sessions"),
    selectAll<SupportTicket>("support_tickets", "*"),
    selectAll<Subscription>("subscriptions", "*"),
    selectAll<{
      customer_id: string;
      investigation: unknown;
      provider: string;
      model: string;
      created_at: string;
    }>(
      "investigations",
      "customer_id,investigation,provider,model,created_at",
      "created_at.desc",
    ),
  ]);

  const custBy = new Map(customers.map((c) => [c.customer_id, c]));
  const caseBy = new Map(cases.map((c) => [c.customer_id, c]));
  const usageBy = group(usage);
  const ticketsBy = group(tickets);
  const subsBy = group(subs);

  // Newest row per customer: the table is a history, and grading a superseded
  // investigation alongside its replacement would double-count.
  const latest = new Map<string, (typeof stored)[number]>();
  for (const row of stored) {
    if (!latest.has(row.customer_id)) latest.set(row.customer_id, row);
  }

  const inputs: GradeInput[] = [];
  for (const row of latest.values()) {
    const customer = custBy.get(row.customer_id);
    if (!customer) continue;
    const u = (usageBy.get(row.customer_id) ?? [])
      .slice()
      .sort((a, b) => a.date.localeCompare(b.date));
    const t = ticketsBy.get(row.customer_id) ?? [];
    const s = subsBy.get(row.customer_id) ?? [];

    inputs.push({
      customerId: row.customer_id,
      provider: row.provider,
      model: row.model,
      stored: row.investigation,
      expectedRecommendation: caseBy.get(row.customer_id)
        ?.expected_recommendation,
      pkg: buildEvidencePackage({
        customerId: row.customer_id,
        company: customer.company,
        plan: customer.plan,
        mrr: customer.mrr,
        industry: customer.industry,
        companySize: customer.company_size,
        signupDate: customer.signup_date,
        recordedThrough: getLatestRecordedDate(u),
        assessment: scoreCustomer({ usage: u, tickets: t, subscriptions: s }),
        tickets: t,
        charges: s,
      }),
    });
  }

  inputs.sort((a, b) => a.customerId.localeCompare(b.customerId));
  const report = evaluateAi(inputs);
  const t = report.totals;

  console.log(`graded ${t.graded} stored investigations`);
  console.log(`  valid shape        ${t.valid}/${t.graded}`);
  console.log(
    `  fully grounded     ${t.fullyGrounded}/${t.valid} (mean ${t.meanGrounding.toFixed(3)})`,
  );
  console.log(`  phantom entities   ${t.withPhantoms} cases`);
  console.log(`  uncited claims     ${t.uncitedClaims}`);
  console.log(
    `  counter-case used  ${t.contradictingUsed}/${t.contradictingAvailable}`,
  );
  console.log(
    `  vs risk band       ${t.aligned} aligned, ${t.escalated} escalated, ${t.deEscalated} de-escalated`,
  );
  console.log(`  uncertainty right  ${t.insufficientAppropriate}/${t.valid}`);
  console.log(
    `  vs human grading   ${report.vsGroundTruth.agree}/${report.vsGroundTruth.compared}`,
  );

  if (DRY) {
    console.log("\n(dry run — EVALUATION-AI.md not written)");
    return;
  }
  const out = join(ROOT, "EVALUATION-AI.md");
  writeFileSync(out, render(report), "utf8");
  console.log(`\nwrote ${out}`);
})();
