/**
 * Phase 7 — grades the risk engine and writes EVALUATION.md.
 *
 * Reads the committed seed CSVs, not Supabase. That is deliberate: the grade
 * has to be reproducible by anyone who clones the repo, with no credentials
 * and no network, and it has to be pinned to a known dataset rather than to
 * whatever the database happens to hold today. Re-run it after any change to
 * the seed or to the engine.
 *
 *   npm run evaluate          print the report and write EVALUATION.md
 *   npm run evaluate -- --dry print only
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  FLAG_THRESHOLD,
  evaluate,
  type AccountData,
  type EvaluationReport,
} from "../lib/evaluation";
import { RISK_LEVEL_THRESHOLDS } from "../lib/constants";
import type {
  CustomerOutcome,
  EvaluationCase,
  SupportTicket,
  Subscription,
  UsageDaily,
} from "../lib/types";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SEED = join(ROOT, "supabase", "seed");
const DRY = process.argv.includes("--dry");

/**
 * Accounts whose usage or gradings were authored by hand rather than
 * generated. Any metric that includes them is partly self-fulfilling, so the
 * report names them instead of quietly folding them in.
 */
const CONSTRUCTED = ["C028", "C035", "C038", "C042"];

/** RFC 4180. A bare empty field is NULL; a quoted one is an empty string. */
function parseCSV(text: string): (string | null)[][] {
  const rows: (string | null)[][] = [];
  let row: (string | null)[] = [];
  let cur = "";
  let quoted = false;
  let wasQuoted = false;
  let i = 0;

  const endField = () => {
    row.push(wasQuoted ? cur : cur === "" ? null : cur);
    cur = "";
    wasQuoted = false;
  };

  while (i < text.length) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          cur += '"';
          i += 2;
          continue;
        }
        quoted = false;
        i++;
        continue;
      }
      cur += ch;
      i++;
      continue;
    }
    if (ch === '"') {
      quoted = true;
      wasQuoted = true;
      i++;
      continue;
    }
    if (ch === ",") {
      endField();
      i++;
      continue;
    }
    if (ch === "\n") {
      endField();
      rows.push(row);
      row = [];
      i++;
      continue;
    }
    if (ch === "\r") {
      i++;
      continue;
    }
    cur += ch;
    i++;
  }
  if (cur !== "" || row.length > 0) {
    endField();
    rows.push(row);
  }
  return rows;
}

function readTable<T>(file: string, numeric: string[] = []): T[] {
  const rows = parseCSV(readFileSync(join(SEED, file), "utf8"));
  const header = rows[0].map((h) => String(h));
  return rows.slice(1).map((r) => {
    const obj: Record<string, unknown> = {};
    header.forEach((h, i) => {
      const raw = r[i];
      obj[h] = numeric.includes(h) ? Number(raw ?? 0) : (raw ?? "");
    });
    return obj as T;
  });
}

function groupBy<T extends { customer_id: string }>(rows: T[]) {
  const m = new Map<string, T[]>();
  for (const r of rows) {
    const l = m.get(r.customer_id);
    if (l) l.push(r);
    else m.set(r.customer_id, [r]);
  }
  return m;
}

const pct = (n: number) => `${(n * 100).toFixed(0)}%`;

/** high < medium < low, for deciding whether a disagreement is under or over. */
const LEVEL_RANK: Record<string, number> = { high: 0, medium: 1, low: 2 };

function render(report: EvaluationReport, datasetNote: string): string {
  const { churn, leadTime, labelAgreement, falsePositiveCases, byCaseType } =
    report;

  const lines: string[] = [];
  const p = (s = "") => lines.push(s);

  p("# Evaluation — how good is the risk engine?");
  p();
  p(
    "Generated by `npm run evaluate` from the committed seed in `supabase/seed/`.",
  );
  p(
    "No database and no credentials are involved, so this is reproducible from a",
  );
  p("clean clone. " + datasetNote);
  p();
  p(
    `An account is **flagged** when it scores ${FLAG_THRESHOLD} or above — the point at which the`,
  );
  p(
    `dashboard stops calling it low risk and a CSM is told to look. \`high\` starts at`,
  );
  p(`${RISK_LEVEL_THRESHOLDS.high}.`);
  p();

  /* --- Headline ---------------------------------------------------- */
  p("## Did it catch the accounts that left?");
  p();
  p(
    `**${churn.flaggedAtChurn} of ${churn.total}** churned accounts were flagged as of their churn date ` +
      `(recall ${pct(churn.recall)}), and ${churn.highAtChurn} scored \`high\`.`,
  );
  p();
  p(
    "Each is replayed with `asOf` set to its churn date. Scoring a churned account",
  );
  p(
    "against today's data would ask whether the engine notices an account stopped",
  );
  p(
    "existing months ago, which is not a useful question. The question is whether it",
  );
  p("would have raised a hand while there was still something to do.");
  p();
  p(
    "| Account | Churned | Score | Level | Confidence | Days observed | Case type |",
  );
  p("| --- | --- | --- | --- | --- | --- | --- |");
  for (const a of churn.accounts) {
    p(
      `| ${a.customerId} | ${a.churnedOn} | ${a.score} | ${a.level} | ${a.confidence} | ${a.observedDays} | \`${a.caseType}\` |`,
    );
  }
  p();

  const misses = churn.accounts.filter((a) => !a.flagged);
  if (misses.length) {
    p("### The misses");
    p();
    for (const m of misses) {
      p(
        `- **${m.customerId}** scored ${m.score} (\`${m.caseType}\`) — ` +
          (m.caseType === "unobservable_limitation"
            ? "expected. Nothing in usage, support or billing preceded this loss, which is the case the dataset includes on purpose."
            : "a genuine miss worth reading the account for."),
      );
    }
    p();
  }

  /* --- Lead time ---------------------------------------------------- */
  p("## How early could it have known?");
  p();
  p(
    "The same accounts, replayed at fixed horizons before their churn date. This is",
  );
  p(
    "the metric that matters operationally: a flag raised the week an account leaves",
  );
  p("is not a rescue.");
  p();
  p("| Days before churn | Observable | Flagged | Recall at horizon |");
  p("| --- | --- | --- | --- |");
  for (const r of leadTime) {
    p(
      `| ${r.daysBefore === 0 ? "at churn" : `${r.daysBefore}d`} | ${r.evaluated} | ${r.flagged} | ${r.evaluated ? pct(r.flagged / r.evaluated) : "n/a"} |`,
    );
  }
  p();
  p(
    "**Observable** excludes accounts whose records do not reach back that far — counting",
  );
  p(
    "them as misses would understate the engine for data it never had. That column",
  );
  p("shrinking at longer horizons is the honest limit of this dataset.");
  p();
  /* --- Non-monotonicity ------------------------------------------- */
  const faded = churn.accounts.filter(
    (a) => a.peakScore > a.score && a.peakDaysBefore > 0,
  );
  if (faded.length) {
    p("### The score is not monotonic in time");
    p();
    p(
      "Recall at 14 days is higher than recall at the churn date itself. That is not",
    );
    p(
      "a quirk of the harness — these accounts scored *worse* earlier than they did at",
    );
    p("the end:");
    p();
    p("| Account | Peak score | When | Score at churn | Flagged at churn |");
    p("| --- | --- | --- | --- | --- |");
    for (const a of faded) {
      p(
        `| ${a.customerId} | ${a.peakScore} | ${a.peakDaysBefore}d before | ${a.score} | ${a.flagged ? "yes" : "**no**"} |`,
      );
    }
    p();
    p(
      "Two of the three usage signals compare the last 30 days against the 30 before",
    );
    p(
      "them, so an account that dips and then partially recovers reads as healthy again",
    );
    p(
      "— even when the dip was the warning and the recovery was somebody exporting",
    );
    p("their data before leaving.");
    p();
    p(
      "This is the clearest actionable finding here. A `peak risk in the last 90 days`",
    );
    p(
      "signal, or simply not letting a recovery clear a recent high-water mark, would",
    );
    p(
      "catch it. Worth noting the current engine would need to carry state across runs",
    );
    p(
      "to do that — which is exactly what the `risk_assessments` history table exists",
    );
    p("for, and is not yet used for.");
    p();
  }

  const earliest = churn.accounts
    .filter((a) => a.firstFlaggedDaysBefore !== null)
    .sort(
      (a, b) =>
        (b.firstFlaggedDaysBefore ?? 0) - (a.firstFlaggedDaysBefore ?? 0),
    );
  if (earliest.length) {
    p("Earliest horizon at which each account would have been flagged:");
    p();
    for (const a of earliest) {
      p(
        `- **${a.customerId}** — ${a.firstFlaggedDaysBefore === 0 ? "only at churn" : `${a.firstFlaggedDaysBefore} days before`}`,
      );
    }
    p();
  }

  /* --- Label agreement --------------------------------------------- */
  p("## Does it agree with the labelled gradings?");
  p();
  p(
    `Exact match on **${labelAgreement.exact} of ${labelAgreement.total}** accounts (${pct(labelAgreement.accuracy)}); ` +
      `${labelAgreement.withinOneBand} land within one band.`,
  );
  p();
  p("| Expected | Engine said | Accounts |");
  p("| --- | --- | --- |");
  for (const c of labelAgreement.confusion) {
    const mark = c.expected === c.actual ? "" : " ←";
    p(`| ${c.expected} | ${c.actual}${mark} | ${c.count} |`);
  }
  p();
  const under = labelAgreement.confusion
    .filter((c) => (LEVEL_RANK[c.expected] ?? 9) < (LEVEL_RANK[c.actual] ?? 9))
    .reduce((n, c) => n + c.count, 0);
  const over = labelAgreement.confusion
    .filter((c) => (LEVEL_RANK[c.expected] ?? 9) > (LEVEL_RANK[c.actual] ?? 9))
    .reduce((n, c) => n + c.count, 0);
  const mediumToLow =
    labelAgreement.confusion.find(
      (c) => c.expected === "medium" && c.actual === "low",
    )?.count ?? 0;
  const mediumTotal = labelAgreement.confusion
    .filter((c) => c.expected === "medium")
    .reduce((n, c) => n + c.count, 0);

  p(
    `The errors are not symmetric. ${under} accounts were scored **lower** than their label ` +
      `and ${over} **higher**, and the bulk of the disagreement sits in one cell: ` +
      `${mediumToLow} of ${mediumTotal} accounts graded \`medium\` scored \`low\`.`,
  );
  p();
  p(
    "That is the engine's real weakness — the extremes are clean and the middle band",
  );
  p(
    "is under-sensitive. Something graded `monitor` by a human is an account with a",
  );
  p(
    "mild, ambiguous signal, which is exactly the shape the additive thresholds round",
  );
  p(
    "down to nothing: two minor signals at 8 points each land at 16, below the 25",
  );
  p(
    "needed to surface. Worth fixing on this evidence rather than by instinct — but",
  );
  p(
    "note that lowering the band to catch them would also pull in the retained",
  );
  p("accounts in the section below.");
  p();
  p(
    "`expected_risk_level` is a human grading, not a second engine. Disagreement is",
  );
  p(
    "not automatically an engine error — the labels were written from the whole",
  );
  p(
    "account including its outcome, and the engine is deliberately blind to that.",
  );
  p();

  /* --- False positives --------------------------------------------- */
  p("## Does it cry wolf?");
  p();
  p(
    `Of ${falsePositiveCases.total} accounts labelled \`false_positive_risk\` — retained customers that look ` +
      `alarming on the surface — the engine flagged **${falsePositiveCases.flagged}**, ` +
      `${falsePositiveCases.flaggedHigh} of them \`high\`.`,
  );
  p();
  p(
    "This is the expensive mistake in a retention tool. A missed churn costs one",
  );
  p(
    "account; a worklist full of customers who were never leaving costs the team's",
  );
  p("trust in the tool, and they stop opening it.");
  p();
  p("| Account | Score | Level |");
  p("| --- | --- | --- |");
  for (const a of falsePositiveCases.accounts) {
    p(`| ${a.customerId} | ${a.score} | ${a.level} |`);
  }
  p();

  /* --- Per case type ----------------------------------------------- */
  p("## By case type");
  p();
  p(
    "The dataset labels each account with the kind of case it is, which is what makes",
  );
  p(
    "a bare accuracy figure misleading: some of these the engine is *supposed* to miss.",
  );
  p();
  p("| Case type | Accounts | Flagged | Expected behaviour |");
  p("| --- | --- | --- | --- |");
  for (const r of byCaseType) {
    p(
      `| \`${r.caseType}\` | ${r.total} | ${r.flagged} | ${r.expectation ?? "—"} |`,
    );
  }
  p();

  /* --- Caveats ------------------------------------------------------ */
  p("## What these numbers are not");
  p();
  p(
    "**The dataset is synthetic.** Every company is invented. These figures say the",
  );
  p(
    "engine behaves as designed on data shaped to contain the cases it targets. They",
  );
  p("do not predict its performance on a real customer book.");
  p();
  p(
    `**${report.constructed.length} accounts were authored by hand** (${report.constructed.join(", ")}) to make ` +
      "specific branches reachable — a recent signup with too little history to judge, " +
      "two active accounts in genuine decline, and one account given tickets so its " +
      "grading had evidence to stand on. Any metric including them is partly " +
      "self-fulfilling: the data was shaped so the engine would find something, and " +
      "then it found it.",
  );
  p();
  p(
    "**Ten churned accounts is a small denominator.** One account moving changes",
  );
  p(
    `recall by ${pct(1 / Math.max(1, report.churn.total))}. Treat the lead-time table as a shape, not a measurement.`,
  );
  p();
  p(
    "**The thresholds were not fitted to these labels.** 50 and 25 were chosen before",
  );
  p(
    "this harness existed and have not been tuned against it, which is why the",
  );
  p(
    "agreement figure is worth reading at all. Tuning them to raise it would make the",
  );
  p("number meaningless.");
  p();

  return lines.join("\n") + "\n";
}

/* --- Load, grade, write --------------------------------------------- */
const customers = readTable<{ customer_id: string }>("01_customers.csv", [
  "mrr",
]);
const usage = readTable<UsageDaily>("02_usage_daily.csv", [
  "logins",
  "sessions",
  "key_actions",
  "feature_usage",
]);
const tickets = readTable<SupportTicket>("03_support_tickets.csv");
const subscriptions = readTable<Subscription>("04_subscriptions.csv", ["mrr"]);
const outcomes = readTable<CustomerOutcome>("05_customer_outcomes.csv");
const cases = readTable<EvaluationCase>("06_evaluation_cases.csv");

const usageBy = groupBy(usage);
const ticketsBy = groupBy(tickets);
const subsBy = groupBy(subscriptions);

const data = new Map<string, AccountData>();
for (const c of customers) {
  data.set(c.customer_id, {
    usage: (usageBy.get(c.customer_id) ?? [])
      .slice()
      .sort((a, b) => a.date.localeCompare(b.date)),
    tickets: ticketsBy.get(c.customer_id) ?? [],
    subscriptions: subsBy.get(c.customer_id) ?? [],
  });
}

const dates = usage.map((u) => u.date).sort();
const datasetNote =
  `Dataset: ${customers.length} customers, ${usage.length} usage rows ` +
  `spanning ${dates[0]} to ${dates[dates.length - 1]}.`;

const report = evaluate({ outcomes, cases, data, constructed: CONSTRUCTED });

console.log(
  `churn recall     ${report.churn.flaggedAtChurn}/${report.churn.total} (${pct(report.churn.recall)}), ${report.churn.highAtChurn} high`,
);
console.log(
  `label agreement  ${report.labelAgreement.exact}/${report.labelAgreement.total} (${pct(report.labelAgreement.accuracy)}) exact, ${report.labelAgreement.withinOneBand} within one band`,
);
console.log(
  `false positives  ${report.falsePositiveCases.flagged}/${report.falsePositiveCases.total} flagged, ${report.falsePositiveCases.flaggedHigh} high`,
);
for (const r of report.leadTime) {
  console.log(
    `  ${String(r.daysBefore).padStart(3)}d before churn: ${r.flagged}/${r.evaluated} flagged (${r.notObservable} not observable)`,
  );
}

if (DRY) {
  console.log("\n(dry run — EVALUATION.md not written)");
} else {
  const out = join(ROOT, "EVALUATION.md");
  writeFileSync(out, render(report, datasetNote), "utf8");
  console.log(`\nwrote ${out}`);
}
